### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by szepeviktor** [mdom/dategrep#23] opened 2015-11-25 11:11 UTC
@mdom Good morning!

I have an infinite loop on this request. (one line)
Please help me.

```
217.13.101.170 - - [24/Nov/2015:18:41:13 +0100] "GET /https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunhttps://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunhttps://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunkaido.hu/https://olmunk" 414 0 "-" "-"
```

**Comment by mdom** [comment] 2015-11-26 07:29
Hi Viktor,

I am travelling around for the next three weeks and won't be able to take a look. Sorry, but I'll check as soon as possible. 

Cheers, Mario

**Comment by mdom** [comment] 2015-12-16 13:11
I can't reproduce that here. Which version of dategrep are you using? And can you paste the complete command line? Can you shorten the line and still reproduce the loop?

**Comment by szepeviktor** [comment] 2015-12-16 13:48
v0.54
```
    nice /usr/local/bin/dategrep --format apache --multiline \
        --from "1 day ago at 06:25:00" --to "06:25:00" "$ACCESS_LOG"
```
It runs in cron.daily.
:cry: I cannot reproduce on the original log file, back from November.
The symptom was that dategrep consumed a a whole CPU core for hours, I've killed it manually.

**Comment by mdom** [comment] 2015-12-16 14:30
Mhh, too bad. Would be good the find the cause. I close the issue and we just hope we can reproduce it next time, okay?

**Comment by szepeviktor** [comment] 2015-12-16 14:31
OK

**Comment by szepeviktor** [comment] 2016-03-09 12:02
@mdom I've got it now:
```
$ date -u
Wed Mar  9 11:59:23 UTC 2016
$ /usr/local/bin/dategrep --format apache --multiline --from "1 day ago at 06:25:00" --to "06:25:00" /tmp/apache.log
```
Here it is: http://www.szepe.net/vendors/apache.log

**Comment by mdom** [comment] 2016-03-10 10:36
I'm very sorry but i still can't reproduce the endless loop here. Would it be possible to get me access on a system where this is reproducible? Or can you use the perl debugger to get a stracktrace?

**Comment by szepeviktor** [comment] 2016-03-10 10:42
Could it be perl v5.10.1 ??

**Comment by szepeviktor** [comment] 2016-03-10 11:31
Or Date::Manip 6.11?

**Comment by szepeviktor** [comment] 2016-03-10 11:36
I've installed old perl on a fresh Debian VPS, but I can't reproduce neither.

**Comment by szepeviktor** [comment] 2016-03-10 11:37
I think I have to upgrade my server.
Sorry for the noise.

**Comment by mdom** [comment] 2016-03-10 12:17
I'll build perl 5.10 when i have time and check if i can reproduce in combination with Date::Manip 6.11. can you

**Comment by szepeviktor** [comment] 2016-06-29 11:07
Now I got it - I think
1. set your clock to Wed, 29 Jun 2016 11:05:46 +0000
1. read you mail (logs)
1. issue `dategrep --format "%a %b %d %T(.[0-9]+)? %Y" --multiline --from "1 day ago at 06:25:00" --to "06:25:00" kkv-batman-ssl-error.log.1 kkv-batman-ssl-error.log`
1. infinite loop!

**Comment by mdom** [comment] 2016-07-01 15:10
Thanks for all your effort but i can still not reproduce the probleme here. I get exactly the lines i would expect and then dategrep terminates. Is that still happening with perl 5.10 or did you upgrade your server?

**Comment by szepeviktor** [comment] 2016-07-01 15:25
I use Debian stable: perl 5.20.2-3+deb8u5

I've got a 100% CPU!

**Comment by szepeviktor** [comment] 2016-07-01 15:27
:smile: Now I use `timeout 60 dategrep ...` or `logtail2`.

**Comment by mdom** [comment] 2016-07-01 15:45
This problem will be hard to debug without access to a system or a stacktrace. Could you use the perl debugger to step through dategrep to see where it loops? Or maybe install a SIGINT handler to dump the stacktrace when you send sigint to dategrep? You could also try dategrep2, but i'm pretty sure strptime(3) does not handle fractional seconds.

**Comment by szepeviktor** [comment] 2016-07-01 15:59
Thank you.
Next time it bites me, I'll start debugging.

**Comment by szepeviktor** [comment] 2016-10-03 08:09
Hello @mdom !
My latest finding is a strace
```
lseek(6, 19641, SEEK_SET)               = 19641
lseek(6, 0, SEEK_CUR)                   = 19641
lseek(6, 8192, SEEK_SET)                = 8192
lseek(6, 0, SEEK_CUR)                   = 8192
read(6, "h() in /home/onlinemunkaido.hu/website/html/app/frontend/controller/AssignmentPlannerController.php on line 352\\nPHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/onlinemunka"..., 8192) = 8192
read(6, "nnerController.php on line 352\\nPHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/onlinemunkaido.hu/website/html/app/frontend/controller/AssignmentPlannerController.php on li"..., 8192) = 8192
```
Does it tell you anything more?

**Comment by mdom** [comment] 2016-10-03 11:03
Can you send me the complete strace output?

Cheers, Mario

**Comment by szepeviktor** [comment] 2016-10-03 11:12
I've written a script that detects cron jobs running for more than 50 minutes.

The out put was the above repeated *forever*. I had to kill the process.

**Comment by mdom** [comment] 2016-10-04 17:35
On Mon, Oct 03, 2016 at 04:12:18AM -0700, Viktor Szépe wrote:
> I've written a script that detects cron jobs running for more than 50 minutes.
> The out put was the above repeated *forever*. I had to kill the process.

Thanks, that looks super helpfull, i try to find a code path that
results in those system call. Can take a few days though.

Cheers, Mario

**Closed** 2016-10-06 09:34 UTC

**Comment by mdom** [comment] 2016-10-06 09:38
Dategrep entered an infinite loop in multiline mode when a line was longer than the blocksize of the underlying filesystem. I couldn't reproduce it, because my blocksize was bigger than the longest line in your files. With a smaller blocksize, i could actually reproduce it. Thanks for sticking so long with me and this issue, @szepeviktor!

**Comment by szepeviktor** [comment] 2016-10-06 12:25
:)

**Comment by szepeviktor** [comment] 2016-10-06 12:26
I hope it gets into 0.57

**Comment by szepeviktor** [comment] 2016-10-06 12:31
How to put together a fatpacked "small"?

**Comment by mdom** [comment] 2016-10-06 12:36
Yeah, sure, no reason not to put this into the next release. I used App::Fatten to build the fatpacked scripts but it seems to be not longer on cpan. Their are several alternatives, but i need some time to evaluate those.

**Comment by szepeviktor** [comment] 2016-10-06 12:42
Thank you.
I've just hacked your commit into the fatpacked "small".

**Comment by mdom** [comment] 2016-10-07 15:32
I just uploaded 0.57.

**Comment by szepeviktor** [comment] 2016-10-07 15:53
Thank you.
