### ISSUE TITLE
Fails with German locale

### ISSUE THREAD

**Issue by andk** [mdom/dategrep#31] opened 2018-08-07 05:42 UTC
As per subject. Sample fail report:

http://www.cpantesters.org/cpan/report/97271888

Statistics: http://analysis.cpantesters.org/reports_by_field?distv=dategrep-2.00;field=env%3ALC_ALL

**Comment by mdom** [comment] 2018-08-07 06:30
I can't reproduce that here with my german locale but it probably depends if `%c` contains `%x` or `%X`. Could you test `perl -MI18N::Langinfo=langinfo,D_T_FMT -E 'say langinfo(D_T_FMT)'`? The patch de6d9eae0d7b9eac5f2f1456dd7efa83bde282be reorders the patterns, so that `%c` is always compiled last. Hope that solves the problem?!

Thanks for the report!

**Comment by andk** [comment] 2018-08-07 18:56
I18N::Langinfo in version 0.13:

``` shell
% for lc in `locale -a`; do
echo -n "$lc    "; LC_ALL=$lc /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.24.2/bb7f/bin/perl -MI18N::Langinfo=langinfo,D_T_FMT -E 'say langinfo(D_T_FMT)'
done             
C       %a %b %e %H:%M:%S %Y
ca_AD.utf8      %a %d %b %Y %T %Z
ca_ES.utf8      %a %d %b %Y %T %Z
ca_ES.utf8@valencia     %a %d %b %Y %T %Z
ca_FR.utf8      %a %d %b %Y %T %Z
ca_IT.utf8      %a %d %b %Y %T %Z
C.UTF-8 %a %b %e %H:%M:%S %Y
de_DE.utf8      %a %d %b %Y %T %Z
en_CA.utf8      %a %d %b %Y %r %Z
en_US.utf8      %a %d %b %Y %r %Z
fr_CA.utf8      %a %d %b %Y %T %Z
POSIX   %a %b %e %H:%M:%S %Y
ru_RU.utf8      %a %d %b %Y %T
```

**Comment by mdom** [comment] 2018-08-07 20:55
Thanks for the info. I just uploaded a new version to cpan that sets LC_TIME to C in all tests, which will probably hide the problem with german locale, but is probably the onle sane way to run the tests. 

I'm still not able to reproduce the problem on any system i have access to. I'll keep you posted :)

**Comment by mdom** [comment] 2018-08-27 07:12
As i can't reproduce the problem on any of my systems, i will close the issue and hope that this was either fixed by some change in the last 20 days or somebody else will also see it.

**Closed by mdom** 2018-08-27 07:12 UTC
